### ISSUE TITLE
Numpy missing

### ISSUE THREAD

**Issue by MateuszMarynowski** [monigenomi/openpgx#3]
After installing package in docker I've got error when using `openpgx update`:
```Traceback (most recent call last):
  File "/usr/local/bin/openpgx", line 5, in <module>
    from openpgx.__main__ import main
  File "/usr/local/lib/python3.8/dist-packages/openpgx/__init__.py", line 8, in <module>
    from numpy import source
```
Please add numpy to setup.py or delete this line, because numpy package is imported but never used.

**Comment by MateuszMarynowski** [comment]
Ok, I created PR with both issues https://github.com/monigenomi/openpgx/pull/5 Please check
